CONFUSIONS = {
    "see": ["see", "sea"],
    "sea": ["sea", "see"],
    "their": ["their", "there"],
    "there": ["there", "their"],
    "its": ["its", "it's"],
    "accept": ["accept", "except"],
    "except": ["except", "accept"],
    "than": ["than", "then"],
    "then": ["then", "than"],
    "your": ["your", "you're"],
    "you're": ["you're", "your"],
    "affect": ["affect", "effect"],
    "effect": ["effect", "affect"],
    "lose": ["lose", "loose"],
    "loose": ["loose", "lose"],
    "principal": ["principal", "principle"],
    "principle": ["principle", "principal"],
    "weather": ["weather", "whether"],
    "whether": ["whether", "weather"],
    "to": ["to", "too", "two"],
    "too": ["too", "to", "two"],
    "two": ["two", "to", "too"],
}
